### ISSUE TITLE
Dead

### ISSUE THREAD

**Issue by crazybytes** [pololu/nixcrpkgs#2]
This thing is dead.

Fetched 4,417 kB in 4s (1,072 kB/s)
Reading package lists... Done
root@WAKKAWAKKA:~# sudo curl https://nixos.org/nix/install | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2476  100  2476    0     0   6060      0 --:--:-- --:--:-- --:--:--  6068
downloading Nix 2.2.2 binary tarball for x86_64-linux from 'https://nixos.org/releases/nix/nix-2.2.2/nix-2.2.2-x86_64-linux.tar.bz2' to '/tmp/nix-binary-tarball-unpack.CIPuaDUvda'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22.5M  100 22.5M    0     0  4877k      0  0:00:04  0:00:04 --:--:-- 5163k
\e[1;31mwarning: installing Nix as root is not supported by this script!\e[0m
performing a single-user installation of Nix...
copying Nix to /nix/store.................................
initialising Nix database...
warning: the group 'nixbld' specified in 'build-users-group' does not exist
warning: the group 'nixbld' specified in 'build-users-group' does not exist
warning: the group 'nixbld' specified in 'build-users-group' does not exist
installing 'nix-2.2.2'
error: the group 'nixbld' specified in 'build-users-group' does not exist
/tmp/nix-binary-tarball-unpack.CIPuaDUvda/unpack/nix-2.2.2-x86_64-linux/install: unable to install Nix into your default profile
root@WAKKAWAKKA:~#

**Comment by DavidEGrayson** [comment]
I'm sorry you are having trouble installing Nix, but you posted his as an issue on the `nixcrpkgs` project, which is a separate project.  I don't happen to know what you need to do to fix your issue, so maybe you should contact the maintainers of the Nix project instead.

**Comment by crazybytes** [comment]
Thanks for replying.
I'm getting little old and forgot what is was about, but, like 90% of all
source codes never compile at once, on linux its mostly ok, but if you want
to compile under windows, cmake, mingw etc., its always a mess. I like the
Starship Enterprise idea. Like you click once one button, and the process
starts and works out find.

"Computer, compile like i want it"

I've worked like one month to get ffmpeg compiled, and wasted tons of time
on compiling other "thingies'.
There is no order in the jungle....

Op wo 14 aug. 2019 om 19:32 schreef David Grayson <notifications@github.com
